// <auto-generated />
namespace ProctorApiv2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddprioritytoSessionTypesforautoassigning : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddprioritytoSessionTypesforautoassigning));
        
        string IMigrationMetadata.Id
        {
            get { return "201812091452397_Add priority to Session Types for auto assigning"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
